### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by Resoluciones** [PenToPaper/TPPets#2]
Hi!  Plugin is the best for pet management.  Unfortunately I'm getting lag spikes when doing pet operations.  Do you know if there anything that can be done to fix it?

Thanks!

**Comment by PenToPaper** [comment]
If you're running Spigot 1.13, that's probably it, especially if this is a recent performance problem. I don't plan on updating the plugin to 1.13 until Spigot releases a stable version. Hopefully this will be soon

**Comment by Resoluciones** [comment]
Hi PenToPaper, yes, I'm running 1.13.  OK understood.

Thanks for the reply!
